### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by nostorian** [traumatism/get-discord-bots-tokens-with-google#2]
How tf u use this thing

**Comment by lhitori** [comment]
Just Google lol

**Comment by nostorian** [comment]
> Just Google lol

Wdym by just Google?
Should i put the l33t docks thing one by one in Google search?
Like for ex I put this in Google search via copy paste: intitle:"Index of" intext:"node_modules" inurl:discord

And it will give the token?

**Comment by lhitori** [comment]
See: https://en.wikipedia.org/wiki/Google_hacking

**Comment by nostorian** [comment]
well i got my first discord token, but sadly that one didn't have intents turned on so yea the token is useless oof

**Comment by lhitori** [comment]
Of course, the tokens might be outated etc.
But sometimes, if you're lucky, you can easily get some hits.

You can also turn this to Censys, Shodan or even Zoomeye ;)
